# Generated by Django 5.0 on 2023-12-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='statys',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
