# Generated by Django 5.0 on 2023-12-23 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletters', '0002_alter_newsletter_options_newsletter_statys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='statys',
            new_name='status',
        ),
    ]
